"""added reading list change manga to umbrella added provider id to chapter

Revision ID: 01dac694cb37
Revises: dfd1933bde66
Create Date: 2026-03-22 11:04:24.279463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dac694cb37'
down_revision = 'dfd1933bde66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('external_manga_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manga_id', 'provider_id', name='uq_manga_source_manga_provider'),
    sa.UniqueConstraint('provider_id', 'external_manga_id', name='uq_manga_source_provider_external')
    )
    op.create_index(op.f('ix_manga_source_external_manga_id'), 'manga_source', ['external_manga_id'], unique=False)
    op.create_index(op.f('ix_manga_source_manga_id'), 'manga_source', ['manga_id'], unique=False)
    op.create_index(op.f('ix_manga_source_provider_id'), 'manga_source', ['provider_id'], unique=False)
    op.create_table('reading_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('last_chapter_number', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'manga_id', name='uq_reading_list_user_manga')
    )
    op.create_index(op.f('ix_reading_list_manga_id'), 'reading_list', ['manga_id'], unique=False)
    op.execute(
        """
        INSERT INTO manga_source (manga_id, provider_id, external_manga_id, created_at)
        SELECT id, provider_id, 'legacy-' || id::text, NOW()
        FROM manga
        """
    )
    op.add_column('chapters', sa.Column('provider_id', sa.String(), nullable=True))
    op.execute(
        """
        UPDATE chapters AS c
        SET provider_id = m.provider_id
        FROM manga AS m
        WHERE c.manga_id = m.id
        """
    )
    op.alter_column('chapters', 'provider_id', nullable=False)
    op.drop_constraint(op.f('uq_chapters_manga_chapter'), 'chapters', type_='unique')
    op.create_index(op.f('ix_chapters_provider_id'), 'chapters', ['provider_id'], unique=False)
    op.create_unique_constraint('uq_chapters_manga_provider_chapter', 'chapters', ['manga_id', 'provider_id', 'chapter_number'])
    op.drop_index(op.f('ix_manga_provider_id'), table_name='manga')
    op.drop_constraint(op.f('uq_manga_provider_title'), 'manga', type_='unique')
    op.drop_column('manga', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_manga_provider_title'), 'manga', ['provider_id', 'manga_title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_manga_provider_id'), 'manga', ['provider_id'], unique=False)
    op.drop_constraint('uq_chapters_manga_provider_chapter', 'chapters', type_='unique')
    op.drop_index(op.f('ix_chapters_provider_id'), table_name='chapters')
    op.create_unique_constraint(op.f('uq_chapters_manga_chapter'), 'chapters', ['manga_id', 'chapter_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('chapters', 'provider_id')
    op.drop_index(op.f('ix_reading_list_manga_id'), table_name='reading_list')
    op.drop_table('reading_list')
    op.drop_index(op.f('ix_manga_source_provider_id'), table_name='manga_source')
    op.drop_index(op.f('ix_manga_source_manga_id'), table_name='manga_source')
    op.drop_index(op.f('ix_manga_source_external_manga_id'), table_name='manga_source')
    op.drop_table('manga_source')
    # ### end Alembic commands ###
