"""updated reading list

Revision ID: 34d55d0d8469
Revises: 01dac694cb37
Create Date: 2026-03-28 18:26:27.292782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34d55d0d8469'
down_revision = '01dac694cb37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_list_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_list_collection_user_id'), 'reading_list_collection', ['user_id'], unique=False)
    op.create_table('reading_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_list_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('last_chapter_number', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(
        ['reading_list_id'],
        ['reading_list_collection.id'],
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_list_id', 'manga_id', name='uq_rli_list_manga')
    )
    op.create_index(op.f('ix_reading_list_item_manga_id'), 'reading_list_item', ['manga_id'], unique=False)
    op.create_index(op.f('ix_reading_list_item_reading_list_id'), 'reading_list_item', ['reading_list_id'], unique=False)

    conn = op.get_bind()
    conn.execute(
        text(
            """
            INSERT INTO reading_list_collection (user_id, name, created_at, updated_at)
            SELECT user_id, 'My list', MIN(created_at), MAX(updated_at)
            FROM reading_list
            GROUP BY user_id
            """
        )
    )
    conn.execute(
        text(
            """
            INSERT INTO reading_list_item
                (reading_list_id, manga_id, last_chapter_number, created_at, updated_at)
            SELECT rlc.id, rl.manga_id, rl.last_chapter_number, rl.created_at, rl.updated_at
            FROM reading_list rl
            INNER JOIN reading_list_collection rlc
                ON rlc.user_id = rl.user_id AND rlc.name = 'My list'
            """
        )
    )

    op.drop_index(op.f('ix_reading_list_manga_id'), table_name='reading_list')
    op.drop_table('reading_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_chapter_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('reading_list_manga_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reading_list_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_list_pkey')),
    sa.UniqueConstraint('user_id', 'manga_id', name=op.f('uq_reading_list_user_manga'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reading_list_manga_id'), 'reading_list', ['manga_id'], unique=False)
    op.drop_index(op.f('ix_reading_list_item_reading_list_id'), table_name='reading_list_item')
    op.drop_index(op.f('ix_reading_list_item_manga_id'), table_name='reading_list_item')
    op.drop_table('reading_list_item')
    op.drop_index(op.f('ix_reading_list_collection_user_id'), table_name='reading_list_collection')
    op.drop_table('reading_list_collection')
    # ### end Alembic commands ###
