name: Deploy Backend to Hugging Face
on:
  push:
    branches: [main]
    paths:
      - 'backend/**' # Only run when files in the backend folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          lfs: true

      - name: Push Backend to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Push the backend folder to the HF Repo using git subtree
          git branch -D deploy || true

          # Create deploy branch from backend subtree
          git subtree split --prefix backend -b deploy

          # Remove all .png files from the deploy branch
          git filter-branch --index-filter "git rm --cached --ignore-unmatch *.png" deploy
          
          # Force push the local 'deploy' branch to the remote 'main' branch
          git push https://tonyliu404:$HF_TOKEN@huggingface.co/spaces/tonyliu404/Manglify_Backend deploy:main --force

          # Delete the temporary local branch
          git branch -D deploy