name: Deploy Backend to Hugging Face
on:
  push:
    branches: [main]
    paths:
      - 'backend/**' # Only run when files in the backend folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push Backend to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Identify the HF Repo URL (Replace with your actual Space name)
          HF_REPO="https://tonyliu404:$HF_TOKEN@huggingface.co/spaces/tonyliu404/Manglify_Backend"
          # 2. Push the backend folder to the HF Repo using git subtree
          git subtree split --prefix backend -b deploy
          
          # 3. Force push the local 'deploy' branch to the remote 'main' branch
          git push "$HF_REPO" deploy:main --force
          
          # 4. Delete the temporary local branch
          git branch -D deploy